### ISSUE TITLE
Add count action to controller

### ISSUE THREAD

**Issue by amazeika** [timble/kodekit#131]
Following the idea that you should be able to get all the data through the controller, it kind of makes sense to add a count action to the controller either directly or through a countable controller behavior. This makes the API cleaner to document and explain.

See:

- https://support.joomlatools.com/forums/topic/6896-get-total-number-of-documents-for-a-given-query

**Comment by johanjanssens** [comment]
See: https://github.com/timble/kodekit/commit/4b6ef1e69ec850b1920af9c8fbc766232246d31d
