### ISSUE TITLE
Allow finer control after dispatcher send event

### ISSUE THREAD

**Issue by ercanozkaya** [timble/kodekit#145]
Add an option to echo response contents or return the results.

See following issue: https://github.com/joomlatools/joomlatools-framework/issues/87  for the use case

**Comment by johanjanssens** [comment]
See: https://github.com/joomlatools/joomlatools-framework/pull/191

**Comment by johanjanssens** [comment]
@ercanozkaya  Think we can consider this one done as part of https://github.com/timble/kodekit/issues/169 ?

**Comment by ercanozkaya** [comment]
@johanjanssens Agreed, closing this one
