### ISSUE TITLE
Synchronize with Joomlatools Framework

### ISSUE THREAD

**Issue by ercanozkaya** [timble/kodekit#169]
Bring changes from the develop branch of Joomlatools Framework 

See: https://github.com/joomlatools/joomlatools-framework/issues?q=is%3Aopen+is%3Aissue+milestone%3ADevelop
See: https://github.com/joomlatools/joomlatools-framework/issues/190
https://github.com/joomlatools/joomlatools-framework/issues/181
https://github.com/joomlatools/joomlatools-framework/issues/212
https://github.com/joomlatools/joomlatools-framework/issues/220
https://github.com/joomlatools/joomlatools-framework/issues/224
https://github.com/joomlatools/joomlatools-framework/issues/198
https://github.com/joomlatools/joomlatools-framework/issues/196
https://github.com/joomlatools/joomlatools-framework/issues/36
https://github.com/joomlatools/joomlatools-framework/pull/227
https://github.com/joomlatools/joomlatools-framework/issues/229
https://github.com/joomlatools/joomlatools-framework/issues/232
https://github.com/joomlatools/joomlatools-framework/issues/233

**Comment by johanjanssens** [comment]
@ercanozkaya For documentation purposes could you add a reference list of tickets from JT Framework we are syncing to the description?

**Comment by ercanozkaya** [comment]
@johanjanssens Done
