### ISSUE TITLE
Missing getTemplate() in TemplateHelperAbstract

### ISSUE THREAD

**Issue by jebbdomingo** [timble/kodekit#180]

**Comment by ercanozkaya** [comment]
@jebbdomingo This is not a bug. Template helpers no longer have access to the template in Kodekit. Where do you need to access the template?

**Comment by jebbdomingo** [comment]
@ercanozkaya In DOCman's listbox helper, tags and day_range use `getTemplate()->helper()`

**Comment by ercanozkaya** [comment]
@jebbdomingo You can use the following format to replace them:

`$this->createHelper('behavior')->bootstrap(['javascript' => false, 'css' => true]);`
