### ISSUE TITLE
Notice when setting request timezone based on lang headers

### ISSUE THREAD

**Issue by amazeika** [timble/kodekit#184]
DispatcherRequestAbstract::getTimezones() makes a call to locale_get_region which takes the language from ::getLanguage(). This last method does not ensure a IETF valid language tag at all times (when grabbing from Accept-Language header). The current change aims to fix this.

**Comment by amazeika** [comment]
@johanjanssens Ercan and I, we were wondering if this replacement that you do here is strictly necessary? => https://github.com/timble/kodekit/blob/8a3662877aecdb18ecb5c1dffe88d9312f9b909e/code/dispatcher/request/abstract.php#L978

Why not keeping the IETF convention for tags?, i.e. (- instead of _).

**Comment by johanjanssens** [comment]
@amazeika Can you please document your issues better, a description of the problem helps me to understand the nature of the problem and the context in which the changes are being proposed.

**Comment by amazeika** [comment]
@johanjanssens yes, sorry about that. I've updated the description to give you a better understanding of the issue.

Other than that, and hence the question asked below, we find often making the replacement between - and _ on language tags. Is there a reson for using _ instead of -? This would reduce the amount of code as we would be using IETF instead.

**Comment by johanjanssens** [comment]
@amazeika  There is no specific reason for the str_replace, besides at least not as i remember. Could be because of Joomla.

I would update the code as such that the tags are always standard compliant using '-' instead of '_'. 

Does that help?
