### ISSUE TITLE
JSON resource structure

### ISSUE THREAD

**Issue by jebbdomingo** [timble/kodekit#199]
Entity resource(s) generated the wrong route.
see https://github.com/joomlatools/foliolabs-docman/pull/42#issuecomment-510827263

**Comment by ercanozkaya** [comment]
@jebbdomingo could you show me the problem in the JSON output and the expected value please?

**Comment by jebbdomingo** [comment]
@ercanozkaya 

https://github.com/timble/kodekit/blob/master/code/view/json.php#L306
`$view    = $entity->getIdentifier()->name;`

The view resolves to plural `documents` instead of singular `document`. It's because the passed `$entity` is a `ModelEntityRowset` resulting to the following route: `self: "http://docman.test/wp-admin/admin.php?component=docman&view=documents ..."`

In joomlatools-framework, the rowset is iterated processing the route for each entity i.e. `ModelEntityDocument` instead of `ModelEntityRowset`

see https://github.com/joomlatools/joomlatools-framework/blob/556564b6c42784895fe5851c3624bd95704a4d2f/code/libraries/joomlatools/library/view/json.php#L190-L192
```
        foreach ($collection as $entity) {
            $result[] = $this->_getEntity($entity);
        }
```

**Comment by ercanozkaya** [comment]
@jebbdomingo Can you check the `feature/199-entity-route2` branch and see if it fixes the issue? Tried a different fix for the issue?

**Comment by jebbdomingo** [comment]
@ercanozkaya Perfect.
