### ISSUE TITLE
Sync Joomlatools Framework

### ISSUE THREAD

**Issue by amazeika** [timble/kodekit#250]
### List of tickets that got sycned

- Add support for multi-dimensional data to CSV - [341](https://github.com/joomlatools/joomlatools-framework/issues/341)
- Pretty print JSON - [353](https://github.com/joomlatools/joomlatools-framework/issues/353)
-  Add support for ORDER BY RAND() - [362](https://github.com/joomlatools/joomlatools-framework/issues/362)
-  Support relative datetime to set max age - [372](https://github.com/joomlatools/joomlatools-framework/issues/372)
-  Do not force 301 when redirecting - [374](https://github.com/joomlatools/joomlatools-framework/issues/374)  
-  Use identifiers when registering config formats - [376](https://github.com/joomlatools/joomlatools-framework/issues/376)
-  Issue merging identifiers in bootstrapper - [380](https://github.com/joomlatools/joomlatools-framework/issues/380)  
- Issues with referrer-policy - [378](https://github.com/joomlatools/joomlatools-framework/issues/378)
-  Locking referrer bug - [364](https://github.com/joomlatools/joomlatools-framework/issues/364)
-  Add is[Behavior] check to model - [390](https://github.com/joomlatools/joomlatools-framework/issues/390)  
-  KHttpResponse::getMaxAge() returns 0 - [396](https://github.com/joomlatools/joomlatools-framework/issues/396) 
-  Add support for conditions to inline script and style elements - [398](https://github.com/joomlatools/joomlatools-framework/issues/398) 
-  Improve http caching support - [331 ](https://github.com/joomlatools/joomlatools-framework/issues/331)
-  Improve http caching support - [403](https://github.com/joomlatools/joomlatools-framework/issues/403) 
-  Response isNotModified() method fails is response is stale - [409](https://github.com/joomlatools/joomlatools-framework/issues/409) 
-  Refactor cacheable behavior - [411](https://github.com/joomlatools/joomlatools-framework/issues/411) 
-  Responses are always cached - [413](https://github.com/joomlatools/joomlatools-framework/issues/413) 
-  Implement support for Server-Timing header - [415](https://github.com/joomlatools/joomlatools-framework/issues/415)
-  Improve http caching support - [332](https://github.com/joomlatools/joomlatools-framework/pull/332)
-  Add caching support for authentic requests - [417](https://github.com/joomlatools/joomlatools-framework/issues/417) 
-  Improve user object group and role handling - [383](https://github.com/joomlatools/joomlatools-framework/issues/383)
-  Improve http support - [323](https://github.com/joomlatools/joomlatools-framework/issues/323)
-  Implement HTTP client - [321](https://github.com/joomlatools/joomlatools-framework/issues/321) 
-  Add support for MySQL Update_time - [328](https://github.com/joomlatools/joomlatools-framework/issues/328)
-  Do not escape [ and ] in url's - [314](https://github.com/joomlatools/joomlatools-framework/issues/314)

**Comment by amazeika** [comment]
@johanjanssens Changes made here https://github.com/joomlatools/joomlatools-framework/issues/383 are to be synced somewhere else? I'm ignoring those for now.

**Comment by johanjanssens** [comment]
> @johanjanssens Changes made here [joomlatools/joomlatools-framework#383](https://github.com/joomlatools/joomlatools-framework/issues/383) are to be synced somewhere else? I'm ignoring those for now.

@amazeika Not sure what you mean? These changes can be included in Kodekit to no?

**Comment by amazeika** [comment]
> > @johanjanssens Changes made here [joomlatools/joomlatools-framework#383](https://github.com/joomlatools/joomlatools-framework/issues/383) are to be synced somewhere else? I'm ignoring those for now.
> 
> @amazeika Not sure what you mean? These changes can be included in Kodekit to no?

Most of the changes in that ticket are made against Koowa, so I was wondering if they should be synced, and if they are, if they should be made part of foliokit or to be synced directly on kodekit.

**Comment by johanjanssens** [comment]
Got it. The changes for this issue are two folder, there are API changes for framework, and there are implementation changes for Koowa. You will need to split and only add the none-Koowa changes.  The Koowa changes should then go into Foliokit. Makes sense?

**Comment by amazeika** [comment]
> Got it. The changes for this issue are two folder, there are API changes for framework, and there are implementation changes for Koowa. You will need to split and only add the none-Koowa changes. The Koowa changes should then go into Foliokit. Makes sense?

@johanjanssens Totally

**Comment by amazeika** [comment]
@johanjanssens @ercanozkaya Since the changes on 298 are on hold and were not synced, I beleive that these changes:

- https://github.com/joomlatools/joomlatools-framework/commit/afc23ca5aeb31305ef16974129f2992ea1ad66e5
- https://github.com/joomlatools/joomlatools-framework/commit/4a17e3b0295faba5f0a4492a671c8624bf347be9
- https://github.com/joomlatools/joomlatools-framework/commit/411f24571ce6668ee1d2a229b8801a091f3aa486

need to be added on the CSRF authenticator. Can you please guys confirm?
