### ISSUE TITLE
Refactor CSRF authenticator

### ISSUE THREAD

**Issue by amazeika** [timble/kodekit#252]
Investigate if changes made on https://github.com/joomlatools/joomlatools-framework/issues/298 should be synced into kodekit.

A batch of Joomlatoos Framework tickets were already sycned here => https://github.com/timble/kodekit/issues/250

**Comment by johanjanssens** [comment]
@ercanozkaya Please review in light of https://github.com/timble/kodekit/issues/264

**Comment by ercanozkaya** [comment]
@johanjanssens @amazeika Closing this in favor of #264. The necessary changes are already ported in #264
