### ISSUE TITLE
Refactor CSRF protection 

### ISSUE THREAD

**Issue by ercanozkaya** [timble/kodekit#264]
Our original CSRF protection was based on a 2008 paper and the paper's main CSRF miitigation recommendation was the inclusion of an `Origin` header by the browsers. 12 years later, all modern browsers have the `Origin` header now and we can simply depend on for protection. 

Use "Use of Custom Request Headers" and "Verifying Origin With Standard Headers" mitigation techniques from OWASP guide:
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#verifying-origin-with-standard-headers

**Comment by johanjanssens** [comment]
@ercanozkaya This does make things a lot easier! Little victory.
